language: bash

services: docker

env:
  - VARIANT=node-10
  - VARIANT=node-12
  - VARIANT=node-13
  
before_script:
  - cd "$VARIANT"
  - image="richardregeer/web-development:${VARIANT}"

script:
  - docker build -t "$image" .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push "$image"

after_script:
- docker images
